# Generated by Django 5.2 on 2025-04-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('day', models.CharField(max_length=100)),
                ('task_name', models.CharField(max_length=255)),
                ('assigned_to', models.CharField(max_length=100)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=100)),
                ('is_done', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
