# Generated by Django 5.1.6 on 2025-04-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='content',
        ),
        migrations.RemoveField(
            model_name='report',
            name='id',
        ),
        migrations.AddField(
            model_name='report',
            name='display_month',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='report_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='assigned_to',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='verified_by',
            field=models.CharField(max_length=255),
        ),
    ]
