# Generated by Django 5.1.7 on 2025-04-15 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_report_content_remove_report_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='report_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='task_id',
        ),
        migrations.AlterField(
            model_name='report',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='display_month',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='verified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
