# Generated by Django 5.1.7 on 2025-04-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_report_id_report_id_remove_report_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
