# Generated by Django 5.1.7 on 2025-04-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_report_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='day',
            field=models.CharField(max_length=100),
        ),
    ]
