# Generated by Django 5.1.7 on 2025-04-16 06:28

import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_report_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='display_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='report',
            name='display_month',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['display_month', 'display_year'], name='base_report_display_c0f951_idx'),
        ),
    ]
