# Generated by Django 5.1.7 on 2025-04-16 06:30

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_report_display_year_alter_report_display_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='display_month',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50),
        ),
    ]
