# Generated by Django 5.1.7 on 2025-04-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='static/images/user_profile_pic.png', upload_to='base/media/'),
        ),
    ]
