# Generated by Django 5.2 on 2025-04-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('days_remaining', models.IntegerField()),
                ('status', models.CharField(choices=[('Not Yet Started', 'Not Yet Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Yet Started', max_length=20)),
            ],
        ),
    ]
