# Generated by Django 5.1.6 on 2025-04-23 05:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_donetask_task_alter_donetask_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donetask',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='donetask',
            name='done_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='donetask',
            name='month',
        ),
        migrations.RemoveField(
            model_name='donetask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='donetask',
            name='user',
        ),
        migrations.RemoveField(
            model_name='donetask',
            name='year',
        ),
    ]
