# Generated by Django 5.1.6 on 2025-05-06 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_donetask_unique_together_donetask_done_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoneTask',
        ),
    ]
