# Generated by Django 5.1.6 on 2025-05-06 06:20

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_delete_donetask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='display_year',
            field=models.IntegerField(default=base.models.current_year),
        ),
    ]
