# Generated by Django 5.1.6 on 2025-05-15 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
    ]
