# Generated by Django 5.1.6 on 2025-05-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_notification_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
