# Generated by Django 5.1.6 on 2025-05-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_report_date_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_submitted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
