name: Monthly Reset Tasks

on:
  schedule:
    - cron: '0 16 1 * *'  # Runs at 16:00 UTC (midnight PH time) on the 1st of every month

jobs:
  reset_tasks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django management command to reset tasks
        run: python manage.py reset_tasks